### ISSUE TITLE
RBAC support

### ISSUE THREAD

**Issue by radu-matei** [radu-matei/brigade-eventgrid-gateway#1]
Right now, if you try to use this gateway with a Brigade that was deployed with RBAC, the gateway will not be able to create or get secrets.

**Comment by jskulavik** [comment]
Hi @radu-matei, this repo/idea is just awesome.  Kudos to you for putting it together.  I'd like to jump in and help out (while selfishly learning more Brigade ;-)).  I did run into [this](https://github.com/kubernetes/helm/issues/2872) issue the other day while the core team was at KubeCon.  Once that issue is resolved, or, if we can find a workaround, I'd be happy to try and help.

**Comment by radu-matei** [comment]
Hi, @jskulavik!
I think the issue was solved with the new Helm release, we'd love your contributions here 😄 

Let me know if there is anything I can help you with - here, or in the #brigade channel on the Kubernetes Slack.
